[workspace]

members = [
  "renderer",
  "shader/triangle"
]

exclude = ["rust-gpu"]

[patch.crates-io]
# https://github.com/bitshifter/glam-rs/pull/85
glam = { git = "https://github.com/EmbarkStudios/glam-rs", rev = "d55ff75e91aab01c4fd9808e3ca9c079dfa7315c" }
