[workspace]

members = [
    "renderer",
    "batch-spirv-builder",
    "egui-winit",
    "egui-wgpu"
]

default-members = [
    "renderer"
]

exclude = [
    "rust-gpu",
    "shader/"
]
